Revert profile pictures
Goose-Nest/GT-RevertRebrand pull request #11
Opened 2021-05-14 16:36 UTC by dav1312

Revert profile pictures of people without custom profile pictures

2021-05-14 16:40 UTC, CanadaHonk requested changes

2021-05-14 16:40 UTC, CanadaHonk commented on src/main.css
> +[src="/assets/1f0bfc0865d324c2587920a7d80c609b.png"] {content: url(/assets/6debd47ed13483642cf09e832ed0bc1b.png)}
Please use similar spacing and syntax with the rest of the file.

2021-05-15 10:51 UTC, CanadaHonk approved these changes

2021-05-15 10:53 UTC, CanadaHonk commented
Sorry to ask further, could you use the new restructure. Please add the changes to a file like `src/components/pfps.css`.

2021-05-15 13:10 UTC, DorCoMaNdO commented
Might I request a similar fix for group chats? The "vibrant" colors are a lot more eye catching when I glance at Discord and it tends to be annoying.

2021-05-15 13:16 UTC, CanadaHonk commented
> Might I request a similar fix for group chats? The "vibrant" colors are a lot more eye catching when I glance at Discord and it tends to be annoying.

What pictures? Please make a new issue with examples, thanks.

2021-05-16 08:44 UTC, CanadaHonk commented
> Sorry to ask further, could you use the new restructure. Please add the changes to a file like `src/components/pfps.css`.

Doing this myself; but still thanks for the PR!

2021-05-16 08:44 UTC, closed without merging