Readded old Discord Nitro settings tab style
Goose-Nest/GT-RevertRebrand pull request #2
Opened 2021-05-11 23:42 UTC by kckarnige

2021-05-12 08:29 UTC, Dziurwa14 commented
use vars

2021-05-12 15:12 UTC, CanadaHonk requested changes

2021-05-12 15:12 UTC, CanadaHonk commented on src/main.css
> +    color: #7289da;
Please use CSS variables (already in this file) instead of hard-coded values.

2021-05-20 17:59 UTC, kckarnige commented
Closed due to pointlessness

2021-05-20 17:59 UTC, closed without merging